name: CI

on: [push]

jobs:
  build_image:
    name: Build Docker image
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Build Docker image
        run: docker image build -t hawk-yard .

      - name: Push to Docker hub if stage
        if: github.ref == 'refs/heads/stage'
        run: |
          echo ${{secrets.DOCKER_PASSWORD}} | docker login --username ${{secrets.DOCKER_USERNAME}} --password-stdin ${{secrets.REGISTRY_ADDRESS}}
          docker tag hawk-yard ${{secrets.REGISTRY_NAME}}/hawk-yard:stage
          docker push ${{secrets.REGISTRY_NAME}}/hawk-yard:stage
      - name: Deploy stage
        if: github.ref == 'refs/heads/stage'
        run: |
          curl -X POST -H "Content-Type: application/json" --data "{\"branch\":\"master\",\"secret_token\":\"${{secrets.HAWK_STAGE_DEPLOY_TOKEN}}\"}" https://stage.hawk.so/deploy
